bipedv5:
  # Publish all joint states -----------------------------------
 
  joint_state_controller:
 
    type: joint_state_controller/JointStateController
 
    publish_rate: 500
 
#position_controllers/JointPositionController 
 
  # Position Controllers ---------------------------------------

  lkp:

    type: effort_controllers/JointPositionController

    joint: lkp

    pid: {p: 10000,i: 500, d: 500, i_clamp_max: 5000.0} 

  rkp:

    type: effort_controllers/JointPositionController
 
    joint: rkp
 
    pid: {p: 10000,i: 500, d: 500, i_clamp_max: 5000.0} 
    
  lap:

    type: effort_controllers/JointPositionController
 
    joint: lap
 
    pid: {p: 10000,i: 500, d: 500, i_clamp_max: 5000.0} 
    
  rap:

    type: effort_controllers/JointPositionController
 
    joint: rap
 
    pid: {p: 10000,i: 500, d: 500, i_clamp_max: 5000.0} 

  ly:

    type: effort_controllers/JointPositionController
 
    joint: ly
 
    pid: {p: 5000,i: 500.0, d: 10, i_clamp_max: 500000.0} 

  ry:

    type: effort_controllers/JointPositionController
 
    joint: ry
 
    pid: {p: 5000,i: 500.0, d: 10, i_clamp_max: 500000.0} 

  lh:

    type: effort_controllers/JointPositionController
 
    joint: lh
 
    pid: {p: 5000,i: 500.0, d: 10, i_clamp_max: 500000.0} 



  rh:
 
    type: effort_controllers/JointPositionController
 
    joint: rh
 
    pid: {p: 5000,i: 500.0, d: 10, i_clamp_max: 500000.0} 


  lk:

    type: effort_controllers/JointPositionController
 
    joint: lk
 
    pid: {p: 5000,i: 500.0, d: 10, i_clamp_max: 500000.0} 


  rk:

    type: effort_controllers/JointPositionController
 
    joint: rk
 
    pid: {p: 5000,i: 500.0, d: 10, i_clamp_max: 500000.0} 

  la:

    type: effort_controllers/JointPositionController
 
    joint: la
 
    pid: {p: 1000,i: 20.0, d: 2, i_clamp_max: 50000.0} 
    
  ra:

    type: effort_controllers/JointPositionController
 
    joint: ra
 
    pid: {p: 1000,i: 20.0, d: 2, i_clamp_max: 50000.0}  