#步态参数
step_period : 10.0  #步态周期
double_support_time : 5.0 #双腿支撑时长
step_len : 0.15      #步长
step_sa : 0.13      
ini_height : -0.52    #初始高度
step_height : 0.1    #抬腿高度
ini_len : -0.01    #初始x位置
StepNum : 1000
#运动学杆件长度
L1 : 0.275
L2 : 0.275
#轨迹插值时间
pause_time : 1000  #循环sleep时间(微秒
dt : 0.001
#模式选择
echo : false
setzero: false
ini: true
si: false
static: true