#步态参数
step_period : 16.0  #步态周期
double_support_time : 8 #双腿支撑时长
step_len : 0.08    #步长
step_sa : 0.11  #侧摆     
ini_height : -0.5    #初始高度
step_height : 0.1    #抬腿高度
ini_len : -0.01    #初始x位置
StepNum : 1000
#运动学杆件长度
L1 : 0.29
L2 : 0.29
#轨迹插值时间
pause_time : 20000  #循环sleep时间(微秒
dt : 0.02

T_ini: 3.0
#电机传动比(1控制量对应rad/米)
r0 : 0.00610865
r1 : 0.174533      #10°
r2 : 0.0622098    #3.5643564356435°
#模式选择
echo : false
ini : true
static: true















