#步态参数
step_period : 1.5  #步态周期
double_support_time : 0.5 #双腿支撑时长
step_len : 0.16    #步长
step_sa : 0.08      #侧摆
ini_height : -0.52    #初始高度
step_height : 0.05    #抬腿高度
ini_len : 0.02    #初始x位置
StepNum : 1000
#运动学杆件长度
L1 : 0.275
L2 : 0.275
L3 : 0.065 
Lhe: 0.09
Lto: 0.13
alpha_tot: 1.1
alpha_het: 0.15
#自然步态时间占双腿支撑期的比例
toe_tp: 0.95
heel_tp: 0.5
#双腿支撑期间步长
sl_dsp: 0.1
#轨迹插值时间
pause_time : 1000  #循环sleep时间(微秒
dt : 0.001
#模式选择
echo : false
setzero: false
ini: true
si: false
static: false
Heel_Toe_walk: true